# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 13:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('dtype', models.CharField(max_length=50)),
                ('default', models.TextField()),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.Field(verbose_name=models.TextField()), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='FieldValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
                ('dtype', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Fields')),
            ],
        ),
        migrations.CreateModel(
            name='Insurers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='fieldvalues',
            name='insurres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Insurers'),
        ),
        migrations.AddField(
            model_name='fields',
            name='insurres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Insurers'),
        ),
        migrations.AlterUniqueTogether(
            name='fields',
            unique_together=set([('field_name', 'dtype', 'insurres')]),
        ),
    ]
