# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-03 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180203_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='default',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fields',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
